<?php

namespace Metinet\XtremQUIZZBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{
    public function getAnswersToQuestion($question) {
        return $this->createQueryBuilder('a')
                ->where('a.question = :question')
                ->setParameters(array('question' => $question))
                ->getQuery()
                ->getResult();
    }
}
