<?php

namespace Metinet\XtremQUIZZBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function getnbQuestionParQuizz($idQuizz) {
        return $this->_em->createQuery("
                    SELECT
                            COUNT(i)
                    FROM
                            MetinetXtremQUIZZBundle:Question i
                    WHERE
                            i.quizz = $idQuizz
            ");
    }
}
