<?php

namespace Metinet\XtremQUIZZBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuizzResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzResultRepository extends EntityRepository
{
    private function getNbQuizzLances(){
        $qb = $this->createQueryBuilder('q')
            ->where('q.user = :user')
            ->andWhere('q.quizz = :quizz')
            ->setParameters(array('user' => $user_id, 'quizz' => $quizz_id))
            ->getQuery()
            ->getResult();
        if(count($qb) > 0)
            return $qb[0];
        else
            return null;
    }
    
    public function findByUserIdAndQuizzId($user_id, $quizz_id) {
        $qb = $this->createQueryBuilder('q')
            ->select('q.id')
            ->where('q.user = :user')
            ->andWhere('q.quizz = :quizz')
            ->setParameters(array('user' => $user_id, 'quizz' => $quizz_id))
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
        return $qb;
    }

}
