<?php

namespace Metinet\XtremQUIZZBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function getNbJoueur() {
        return $this->_em->createQuery('
			SELECT
				COUNT(i)
			FROM
				MetinetXtremQUIZZBundle:User i
		');
    }
    
    public function getNbJoueur7jours() {
        return $this->_em->createQuery('
			SELECT
				COUNT(i)
			FROM
				MetinetXtremQUIZZBundle:User i
                        WHERE
                                created_at BETWEEN DATE() - 7 AND DATE()
		');
    }
    
    public function getNbJoueur30jours() {
        return $this->_em->createQuery('
			SELECT
				COUNT(i)
			FROM
				MetinetXtremQUIZZBundle:User i
                        WHERE
                                created_at BETWEEN GETDATE() - 30 and GETDATE()
		');
    }
}
